language: python
python:
 - "3.6.10"
install:
 - make deps
script:
 - make lint
 - make test
 - make docker_build
 - make docker_push
services:
 - docker
deploy:
  provider: heroku
  app: polar-reef-82921
  api_key: ${3f32a625-33ec-428f-a025-42e189db2c74}
